const fs = require('fs');
const path = require('path');

const vendor = (process.env.VENDOR ?? '').trim();
const envFile = path.join(__dirname, 'src', 'environment-gen.ts');

// Ensure directory exists
fs.mkdirSync(path.dirname(envFile), { recursive: true });

const content = `// Auto-generated by generate-env.js - DO NOT EDIT
export const vendor: string = '${vendor}';
`;

fs.writeFileSync(envFile, content);
console.log(`Generated environment.ts with VENDOR = "${vendor}"`);